-- Seed: initial dropdown values
INSERT INTO dropdown_options (category, value, display_order) VALUES
('employment_status', 'Active', 1),
('employment_status', 'Inactive', 2),
('employment_status', 'Out of Project', 3),
('employment_status', 'On Bench', 4),
('employment_status', 'Terminated', 5),
('employment_status', 'On Leave', 6),
('payment_method', 'Payroll Provider (ADP)', 1),
('payment_method', 'Payroll Provider (Gusto)', 2),
('payment_method', 'Payroll Provider (Paychex)', 3),
('payment_method', 'Payroll Provider (Other)', 4),
('payment_method', 'Check', 5),
('payment_method', 'Bank Transfer / ACH', 6),
('payment_method', 'Wire Transfer', 7),
('payment_method', 'Zelle', 8),
('payment_method', 'PayPal', 9),
('payment_method', 'Other', 10),
('expense_type', 'H1B Filing Fee', 1),
('expense_type', 'H1B Premium Processing', 2),
('expense_type', 'H1B Attorney Fee', 3),
('expense_type', 'Green Card Filing', 4),
('expense_type', 'GC Premium Processing', 5),
('expense_type', 'GC Attorney Fee', 6),
('expense_type', 'Visa Stamping', 7),
('expense_type', 'I-140 Filing', 8),
('expense_type', 'I-485 Filing', 9),
('expense_type', 'Background Check', 10),
('expense_type', 'Relocation', 11),
('expense_type', 'Training/Certification', 12),
('expense_type', 'Equipment/Laptop', 13),
('expense_type', 'Travel', 14),
('expense_type', 'Insurance Premium', 15),
('expense_type', 'Other', 16),
('reason_for_payment', 'H1B Reimbursement', 1),
('reason_for_payment', 'H1B Premium Reimbursement', 2),
('reason_for_payment', 'Green Card Reimbursement', 3),
('reason_for_payment', 'GC Premium Reimbursement', 4),
('reason_for_payment', 'Project Without Payroll Reimbursement', 5),
('reason_for_payment', 'Attorney Fee Reimbursement', 6),
('reason_for_payment', 'Visa Stamping Reimbursement', 7),
('reason_for_payment', 'Training Cost Reimbursement', 8),
('reason_for_payment', 'Equipment Reimbursement', 9),
('reason_for_payment', 'Loan Repayment', 10),
('reason_for_payment', 'Penalty / Breach of Contract', 11),
('reason_for_payment', 'Other', 12)
ON CONFLICT (category, value) DO NOTHING;
